name: Update .pot file 🌐

on:
  pull_request:
    branches: [dev]
    paths:
      - "**.php"
      - "**.js"
  workflow_dispatch:

jobs:
  update-pot-file:
    uses: pressbooks/reusable-workflows/.github/workflows/update-pot.yml@main
    secrets: inherit
    with:
      domain: "pressbooks-multi-institution"
      slug: "pressbooks-multi-institution"
      package_name: "Pressbooks Shared Network"
      headers: '{"Report-Msgid-Bugs-To": "https://github.com/pressbooks/pressbooks-multi-institution/issues"}'
