name: Update .mo files

on:
  pull_request:
    branches: [ dev ]
    paths:
      - 'languages/*.po'
  workflow_dispatch:

jobs:
  update-mo-files:
    runs-on: ubuntu-latest
    steps:
      - uses: pressbooks/reusable-workflows/.github/workflows/update-translations.yml@dev
